version: '2.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      cluster.name: test
      discovery.type: single-node
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "true"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    links:
      - elasticsearch:es
    ports:
      - "5601:5601/tcp"
  
  test:
    image: golang:1.11
    working_dir: /go/src/github.com/disaster37/go-kibana-rest
    volumes:
      - .:/go/src/github.com/disaster37/go-kibana-rest
    command: "bash -c \"go test ./... -parallel=1\""
    links:
      - kibana:kb

  build:
    image: golang:1.11
    working_dir: /go/src/github.com/disaster37/go-kibana-rest
    environment:
      http_proxy: $http_proxy
      https_proxy: $https_proxy
    volumes:
      - .:/go/src/github.com/disaster37/go-kibana-rest
    command: "bash -c \"go get github.com/mitchellh/gox && gox -osarch='linux/amd64' -output 'release/kibana-rest_{{.OS}}_{{.Arch}}'\""
  
